source 'https://rubygems.org'
gem 'bundler',            '1.3.5'
gem 'capybara',           '2.2.0'
gem 'selenium-webdriver', '2.38.0'
gem 'rest-client',        '1.6.7'
gem 'json',               '1.8.0'

# BDD Testing
gem 'cucumber',           '1.3.8'
gem 'rspec',              '2.14.1'

