// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.saternos.bookshop.domain;

import com.saternos.bookshop.domain.Author;
import com.saternos.bookshop.domain.AuthorDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect AuthorDataOnDemand_Roo_DataOnDemand {
    
    declare @type: AuthorDataOnDemand: @Component;
    
    private Random AuthorDataOnDemand.rnd = new SecureRandom();
    
    private List<Author> AuthorDataOnDemand.data;
    
    public Author AuthorDataOnDemand.getNewTransientAuthor(int index) {
        Author obj = new Author();
        setName(obj, index);
        return obj;
    }
    
    public void AuthorDataOnDemand.setName(Author obj, int index) {
        String name = "name_" + index;
        obj.setName(name);
    }
    
    public Author AuthorDataOnDemand.getSpecificAuthor(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Author obj = data.get(index);
        Long id = obj.getId();
        return Author.findAuthor(id);
    }
    
    public Author AuthorDataOnDemand.getRandomAuthor() {
        init();
        Author obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Author.findAuthor(id);
    }
    
    public boolean AuthorDataOnDemand.modifyAuthor(Author obj) {
        return false;
    }
    
    public void AuthorDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Author.findAuthorEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Author' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Author>();
        for (int i = 0; i < 10; i++) {
            Author obj = getNewTransientAuthor(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
