// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.saternos.bookshop.domain;

import com.saternos.bookshop.domain.BookDataOnDemand;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect BookDataOnDemand_Roo_Configurable {
    
    declare @type: BookDataOnDemand: @Configurable;
    
}
